### ISSUE TITLE
Parallelisation

### ISSUE THREAD

**Issue by ArthurCamara** [webis-de/ir_axioms#5]
Hi everyone! First of all, this is really nice work, that could potentially put axioms back into fashion =)
However, I've noticed that at least when using the system naively, there is no support for parallel execution (via threads of processes). So, if you want to extract all triples of preferences from, say, the training set of MsMarco, it is unfeasible to be done.

To be more specific, when talking about the axiomatic preferences modules, at least in theory, it should be possible to start a pool of workers and a queue of jobs, where each job is a query (and its corresponding ranking).

Alternatively, I've seen that you mention that ir-axioms is compatible with SLURM commands. How one would go to start a (series of) slurm jobs using it?

Thanks!

**Comment by mam10eks** [comment]
Dear @ArthurCamara,
thanks for the issue.

We will discuss how we can simplify parallel execution in our next meeting, and I guess that SLURM might be the easiest way to go.
In fact, extracting all preferences (or a large enough sample) from the training set of MS MARCO is also something that we wanted to do for a long time.

**Comment by heinrichreimer** [comment]
Parallelisation is definitely one of the most-wanted features for us!
We'll probably have to adapt some of the PyTerrier and Pyserini compat layers but I think the simplest might actually be using [joblib](https://joblib.readthedocs.io/en/latest/index.html).
The biggest disadvantage with that library is that by default it runs on a single host, not multiple machines like Slurm.
However, using its [Spark backend](https://github.com/joblib/joblib-spark) it should also be possible to run on a cluster.
I don't know of any Slurm wrapper for Python that would have the same convenience as using joblib.

**Comment by heinrichreimer** [comment]
Just found another example which uses [Dask](https://distributed.dask.org/en/stable/) with [Dask-Jobqueue](https://jobqueue.dask.org/en/latest/) to connect a Slurm cluster to joblib parallelization:
https://github.com/joblib/joblib/issues/957#issue-517899100

**Comment by ArthurCamara** [comment]
Haven't tried it yet, but there could be an even easier way to do this using multiprocessing. 
From what I can gather, if there are multiple run files here: https://github.com/webis-de/ir_axioms/blob/b9dbd5bff0942b83502635e8a2ad2d849f8ee95f/examples/trec_preferences.py#L139-L146

Then, when we call preferences, maybe we can split this call Into multiple subprocesses?: https://github.com/webis-de/ir_axioms/blob/b9dbd5bff0942b83502635e8a2ad2d849f8ee95f/ir_axioms/backend/pyterrier/experiment.py#L146-L149

I'm not entirely sure how Pyterrier works, and if there could be some blocking element in the Transformer logic, but this seems like the easier/faster way to go about it?

**Comment by heinrichreimer** [comment]
Implemented in 428f1a16534cdbb1e7dfd9a4fa4a528be48e8ad3.
(@ArthurCamara Feel free to re-open this issue if parallelization using PyTerrier's `parallel()` doesn't work for you.)
